development: 
   adapter: mysql2
   encoding: utf8 
   database: db2
   username: root 
   password: root 
production: 
   adapter: mysql2
   encoding: utf8 
   database: db1
   username: root 
   password: root 


 




















# default: &default
#   adapter: postgresql
#   pool: 5
#   username: root
#   password: root
#   timeout: 5000

# development:
#   <<: *default
#   database: blog1s

# production:
#   <<: *default
#   database: blog1s


